module.exports = {
    semi: true,
    singleQuote: true,
    trailingComma: 'all',
    printWidth: 90,
    tabWidth: 2,
    endOfLine: 'lf',
    arrowParens: 'always',
    bracketSpacing: true,
    jsxBracketSameLine: true,
    jsxSingleQuote: true,
    quoteProps: 'as-needed',
    useTabs: true,
    plugins: ['prettier-plugin-tailwindcss'],
};
